# config.py
WIDTH = 800
HEIGHT = 740
FPS = 60

# Vehicle settings
VEHICLE_WIDTH = 20
VEHICLE_HEIGHT = 40
BASE_SPEED = 2.5
MIN_SPEED = 0.8

# Intersection settings
STOP_OFFSET = 70
LANE_WIDTH = 35
DILEMMA_ZONE_DISTANCE = 70
BRAKING_DISTANCE = 40
FIXED_GREEN_DURATION = 10 # This was the missing variable
GREEN_DURATION = 8
YELLOW_DURATION = 2
MIN_GREEN = 4
MAX_GREEN = 15
